package com.tv91;

import com.tv91.features.authentication.p199m.ChangePasswordFragment_GeneratedInjector;
import com.tv91.features.authentication.p200n.LoginFragment_GeneratedInjector;
import com.tv91.features.authentication.p201o.RegisterFragment_GeneratedInjector;
import com.tv91.features.authentication.p202p.ForgetPasswordFragment_GeneratedInjector;
import com.tv91.features.authentication.p204r.VerifyFragment_GeneratedInjector;
import com.tv91.p213u.p214a.p215m.ActorFragment_GeneratedInjector;
import com.tv91.p213u.p214a.p216n.CategoryFragment_GeneratedInjector;
import com.tv91.p213u.p214a.p217o.ChannelFragment_GeneratedInjector;
import com.tv91.p213u.p214a.p218p.ProfileFragment_GeneratedInjector;
import com.tv91.p213u.p214a.p219q.PromotionFragment_GeneratedInjector;
import com.tv91.p213u.p221b.DownloadFragment_GeneratedInjector;
import com.tv91.p213u.p223c.p224f.MovieFragment_GeneratedInjector;
import com.tv91.p213u.p223c.p225g.FavoriteFragment_GeneratedInjector;
import com.tv91.p213u.p223c.p226h.HighlightFragment_GeneratedInjector;
import com.tv91.p213u.p223c.p227i.BaseMoviesFragment_GeneratedInjector;
import com.tv91.p213u.p223c.p228j.MovieSearchFragment_GeneratedInjector;
import com.tv91.p213u.p230d.NewsFragment_GeneratedInjector;
import com.tv91.p213u.p231e.p232g.MemberPromotionFragment_GeneratedInjector;
import com.tv91.p213u.p231e.p234i.PromotionStatementFragment_GeneratedInjector;
import com.tv91.p213u.p231e.p236k.PromotionWithdrawFragment_GeneratedInjector;
import com.tv91.p213u.p237f.p238c.FeedbackListFragment_GeneratedInjector;
import com.tv91.p213u.p237f.p240e.SendFeedbackFragment_GeneratedInjector;
import com.tv91.p213u.p242g.SplashFragment_GeneratedInjector;
import com.tv91.p213u.p244h.p245h.HistoryFragment_GeneratedInjector;
import com.tv91.p213u.p244h.p246i.PaymentFragment_GeneratedInjector;
import com.tv91.p213u.p244h.p247j.PurchaseFragment_GeneratedInjector;
import p262d.p263a.p264b.p265c.FragmentComponent;
import p262d.p263a.p269c.GeneratedComponent;

/* renamed from: com.tv91.h */
/* compiled from: App_HiltComponents */
public abstract class C2321h implements ChangePasswordFragment_GeneratedInjector, LoginFragment_GeneratedInjector, RegisterFragment_GeneratedInjector, ForgetPasswordFragment_GeneratedInjector, VerifyFragment_GeneratedInjector, ActorFragment_GeneratedInjector, CategoryFragment_GeneratedInjector, ChannelFragment_GeneratedInjector, ProfileFragment_GeneratedInjector, PromotionFragment_GeneratedInjector, DownloadFragment_GeneratedInjector, MovieFragment_GeneratedInjector, FavoriteFragment_GeneratedInjector, HighlightFragment_GeneratedInjector, BaseMoviesFragment_GeneratedInjector, MovieSearchFragment_GeneratedInjector, NewsFragment_GeneratedInjector, MemberPromotionFragment_GeneratedInjector, PromotionStatementFragment_GeneratedInjector, PromotionWithdrawFragment_GeneratedInjector, FeedbackListFragment_GeneratedInjector, SendFeedbackFragment_GeneratedInjector, SplashFragment_GeneratedInjector, HistoryFragment_GeneratedInjector, PaymentFragment_GeneratedInjector, PurchaseFragment_GeneratedInjector, FragmentComponent, GeneratedComponent {
}
